
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Aug 18 02:02:35 CST 2024
//----------------------------------------------------

package code;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ELSE = 5;
  public static final int CloseBrace = 18;
  public static final int INT = 3;
  public static final int WHILE = 6;
  public static final int ERROR = 30;
  public static final int OpenBrace = 17;
  public static final int Args = 25;
  public static final int IF = 4;
  public static final int Multiplication = 12;
  public static final int CloseParenthesis = 16;
  public static final int DO = 8;
  public static final int Semicolon = 27;
  public static final int STRING = 2;
  public static final int Main = 26;
  public static final int CloseBracket = 20;
  public static final int Identifier = 28;
  public static final int EOF = 0;
  public static final int Division = 13;
  public static final int OpenBracket = 19;
  public static final int error = 1;
  public static final int Class = 22;
  public static final int Modulo = 14;
  public static final int Subtract = 11;
  public static final int Void = 24;
  public static final int Public = 21;
  public static final int Equal = 9;
  public static final int Static = 23;
  public static final int Add = 10;
  public static final int FOR = 7;
  public static final int OpenParenthesis = 15;
  public static final int Number = 29;
}

