
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Oct 08 08:58:54 CST 2024
//----------------------------------------------------

package code;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Comma = 2;
  public static final int Class = 30;
  public static final int Increment = 15;
  public static final int Void = 32;
  public static final int CloseBrace = 25;
  public static final int GreaterThan = 11;
  public static final int Equal = 10;
  public static final int Static = 31;
  public static final int INT = 4;
  public static final int FOR = 8;
  public static final int Decrement = 16;
  public static final int StringLiteral = 28;
  public static final int Semicolon = 35;
  public static final int CloseParenthesis = 23;
  public static final int Division = 20;
  public static final int IF = 5;
  public static final int Modulo = 21;
  public static final int LessEqualThan = 14;
  public static final int Number = 37;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int GreaterEqualThan = 12;
  public static final int OpenBrace = 24;
  public static final int ERROR = 38;
  public static final int Identifier = 36;
  public static final int Args = 33;
  public static final int Subtract = 18;
  public static final int Public = 29;
  public static final int ELSE = 6;
  public static final int LessThan = 13;
  public static final int CloseBracket = 27;
  public static final int WHILE = 7;
  public static final int Add = 17;
  public static final int STRING = 3;
  public static final int Multiplication = 19;
  public static final int OpenBracket = 26;
  public static final int Main = 34;
  public static final int DO = 9;
  public static final int OpenParenthesis = 22;
}

