
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Aug 18 23:01:27 CST 2024
//----------------------------------------------------

package code;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ELSE = 6;
  public static final int CloseBrace = 19;
  public static final int INT = 4;
  public static final int WHILE = 7;
  public static final int Comma = 2;
  public static final int ERROR = 32;
  public static final int OpenBrace = 18;
  public static final int Args = 27;
  public static final int IF = 5;
  public static final int Multiplication = 13;
  public static final int CloseParenthesis = 17;
  public static final int DO = 9;
  public static final int Semicolon = 29;
  public static final int STRING = 3;
  public static final int Main = 28;
  public static final int CloseBracket = 21;
  public static final int Identifier = 30;
  public static final int EOF = 0;
  public static final int StringLiteral = 22;
  public static final int Division = 14;
  public static final int OpenBracket = 20;
  public static final int error = 1;
  public static final int Class = 24;
  public static final int Modulo = 15;
  public static final int Subtract = 12;
  public static final int Void = 26;
  public static final int Public = 23;
  public static final int Equal = 10;
  public static final int Static = 25;
  public static final int Add = 11;
  public static final int FOR = 8;
  public static final int OpenParenthesis = 16;
  public static final int Number = 31;
}

